refs #182 binは全部スペースインデントにする

diff --git a/bin/zenra b/bin/zenra
--- a/bin/zenra
+++ b/bin/zenra
@@ -8,17 +8,17 @@ command="$1"
 
 case "$command" in
 [a-z0-9]*)
-	shift
-	if test -x "$BINDIR/$command"
-	then
-		exec "$BINDIR/$command" "$@"
-	else
-		echo 1>&2 "${command}: not found."
-	fi
-	;;
+  shift
+  if test -x "$BINDIR/$command"
+  then
+    exec "$BINDIR/$command" "$@"
+  else
+    echo 1>&2 "${command}: not found."
+  fi
+  ;;
 *)
-	echo 1>&2 "${0}: unknown command."
-	;;
+  echo 1>&2 "${0}: unknown command."
+  ;;
 esac
 
 exit 1
